### ISSUE TITLE
Experiment "Stanislav Smirnov lectures. Random walks"

### ISSUE THREAD

**Issue by lounres** [lounres/math-kotlin-experiments#1]
## TODO
- [ ] Rename the experiment 😭
- [ ] Add documentation
- [ ] Different kinds of random walks
  - [ ] 2D:
    - [ ] Square lattice
    - [ ] Triangular lattice
    - [ ] 2D Voronoi diagram on random point sets
    
      *Needs:*
      - 2D Voronoi Diagram (KONE-5)
      - Probability distribution
      
      *Type of random point sets:*
      - [ ] Just set of random points
      - [ ] Prepared regular point set with slight afterward moving of each point
  - [ ] 3D:
    - [ ] Cubic lattice
    - [ ] Tetrahedron lattice
    - [ ] 3D Voronoi diagram on random point sets
    
      *Needs:*
      - 3D Voronoi Diagram (KONE-5)
      - Probability distribution
      
      *Type of random point sets:*
      - [ ] Just set of random points
      - [ ] Prepared regular point set with slight afterward moving of each point
- [ ] Representation of the result
